package com.mattdag.f1.kafka.common.enums

import kotlinx.serialization.Serializable

@Serializable
enum class Driver(val id: Int, val fullname: String) {
    CARLOS_SAINZ(0, "Carlos Sainz"),
    DANIIL_KVYAT(1, "Daniil Kvyat"),
    DANIEL_RICCIARDO(2, "Daniel Ricciardo"),
    FERNANDO_ALONSO(3, "Fernando Alonso"),
    FELIPE_MASSA(4, "Felipe Massa"),
    KIMI_RAIKKONEN(6, "Kimi Räikkönen"),
    LEWIS_HAMILTON(7, "Lewis Hamilton"),
    MAX_VERSTAPPEN(9, "Max Verstappen"),
    NICO_HULKENBURG(10, "Nico Hulkenburg"),
    KEVIN_MAGNUSSEN(11, "Kevin Magnussen"),
    ROMAIN_GROSJEAN(12, "Romain Grosjean"),
    SEBASTIAN_VETTEL(13, "Sebastian Vettel"),
    SERGIO_PEREZ(14, "Sergio Perez"),
    VALTTERI_BOTTAS(15, "Valtteri Bottas"),
    ESTEBAN_OCON(17, "Esteban Ocon"),
    LANCE_STROLL(19, "Lance Stroll"),
    ARRON_BARNES(20, "Arron Barnes"),
    MARTIN_GILES(21, "Martin Giles"),
    ALEX_MURRAY(22, "Alex Murray"),
    LUCAS_ROTH(23, "Lucas Roth"),
    IGOR_CORREIA(24, "Igor Correia"),
    SOPHIE_LEVASSEUR(25, "Sophie Levasseur"),
    JONAS_SCHIFFER(26, "Jonas Schiffer"),
    ALAIN_FOREST(27, "Alain Forest"),
    JAY_LETOURNEAU(28, "Jay Letourneau"),
    ESTO_SAARI(29, "Esto Saari"),
    YASAR_ATIYEH(30, "Yasar Atiyeh"),
    CALLISTO_CALABRESI(31, "Callisto Calabresi"),
    NAOTA_IZUM(32, "Naota Izum"),
    HOWARD_CLARKE(33, "Howard Clarke"),
    WILHEIM_KAUFMANN(34, "Wilheim Kaufmann"),
    MARIE_LAURSEN(35, "Marie Laursen"),
    FLAVIO_NIEVES(36, "Flavio Nieves"),
    PETER_BELOUSOV(37, "Peter Belousov"),
    KLIMEK_MICHALSKI(38, "Klimek Michalski"),
    SANTIAGO_MORENO(39, "Santiago Moreno"),
    BENJAMIN_COPPENS(40, "Benjamin Coppens"),
    NOAH_VISSER(41, "Noah Visser"),
    GERT_WALDMULLER(42, "Gert Waldmuller"),
    JULIAN_QUESADA(43, "Julian Quesada"),
    DANIEL_JONES(44, "Daniel Jones"),
    ARTEM_MARKOLOV(45, "Artem Markelov"),
    TADASUKE_MAKINO(46, "Tadasuke Makino"),
    SEAN_GELAEL(47, "Sean Gelael"),
    NYCK_DE_VRIES(48, "Nyck De Vries"),
    JACK_AITKEN(49, "Jack Aitken"),
    GEORGE_RUSSELL(50, "George Russell"),
    MAXIMILIAN_GUNTHER(51, "Maximilian Günther"),
    NIREI_FUKUZUMI(52, "Nirei Fukuzumi"),
    LUCA_GHIOTTO(53, "Luca Ghiotto"),
    LANDO_NORRIS(54, "Lando Norris"),
    SERGIO_SETTE_CAMARA(55, "Sérgio Sette Câmara"),
    LOUIS_DELETRAZ(56, "Louis Delétraz"),
    ANTONIO_FUOCO(57, "Antonio Fuoco"),
    CHARLES_LECLERC(58, "Charles Leclerc"),
    PIERRE_GASLY(59, "Pierre Gasly"),
    ALEXANDER_ALBON(62, "Alexander Albon"),
    NICHOLAS_LATIFI(63, "Nicholas Latifi"),
    DORIAN_BOCCOLACCI(64, "Dorian Boccolacci"),
    NIKO_KARI(65, "Niko Kari"),
    ROBERTO_MERHI(66, "Roberto Merhi"),
    ARJUN_MAINI(67, "Arjun Maini"),
    ALESSIO_LORANDI(68, "Alessio Lorandi"),
    RUBEN_MEIJER(69, "Ruben Meijer"),
    RASHID_NAIR(70, "Rashid Nair"),
    JACK_TREMBLAY(71, "Jack Tremblay"),
    DEVON_BUTLER(72, "Devon Butler"),
    LUKAS_WEBER(73, "Lukas Weber"),
    ANTONIO_GIOVINAZZI(74, "Antonio Giovinazzi"),
    ROBERT_KUBICA(75, "Robert Kubica"),
    ALAIN_PROST(76, "Alain Prost"),
    AYRTON_SENNA(77, "Ayrton Senna"),
    NOBUHARU_MATSUSHITA(78, "Nobuharu Matsushita"),
    NIKITA_MAZEPIN(79, "Nikita Mazepin"),
    GUANYU_ZHOU(80, "Guanya Zhou"),
    MICK_SCHUMACHER(81, "Mick Schumacher"),
    CALLUM_ILOTT(82, "Callum Ilott"),
    JUAN_MANUEL_CORREA(83, "Juan Manuel Correa"),
    JORDAN_KING(84, "Jordan King"),
    MAHAVEER_RAGHUNATHAN(85, "Mahaveer Raghunathan"),
    TATIANA_CALDERON(86, "Tatiana Calderon"),
    ANTHOINE_HUBERT(87, "Anthoine Hubert"),
    GULIANO_ALESI(88, "Guiliano Alesi"),
    RALPH_BOSCHUNG(89, "Ralph Boschung"),
    MICHAEL_SCHUMACHER(90, "Michael Schumacher"),
    DAN_TICKTUM(91, "Dan Ticktum"),
    MARCUS_ARMSTRONG(92, "Marcus Armstrong"),
    CHRISTIAN_LUNDGAARD(93, "Christian Lundgaard"),
    YUKI_TSUNODA(94, "Yuki Tsunoda"),
    JEHAN_DARUVALA(95, "Jehan Daruvala"),
    GUILHERME_SAMAIA(96, "Gulherme Samaia"),
    PEDRO_PIQUET(97, "Pedro Piquet"),
    FELIPE_DRUGOVICH(98, "Felipe Drugovich"),
    ROBERT_SCHWARTZMAN(99, "Robert Schwartzman"),
    ROY_NISSANY(100, "Roy Nissany"),
    MARINO_SATO(101, "Marino Sato"),
    AIDAN_JACKSON(102, "Aidan Jackson"),
    CASPER_AKKERMAN(103, "Casper Akkerman"),
    JENSON_BUTTON(109, "Jenson Button"),
    DAVID_COULTHARD(110, "David Coulthard"),
    NICO_ROSBERG(111, "Nico Rosberg"),
    OSCAR_PIASTRI(112, "Oscar Piastri"),
    LIAM_LAWSON(113, "Liam Lawson"),
    JURI_VIPS(114, "Juri Vips"),
    THEO_POURCHAIRE(115, "Theo Pourchaire"),
    RICHARD_VERSCHOOR(116, "Richard Verschoor"),
    LIRIM_ZENDELI(117, "Lirim Zendeli"),
    DAVID_BECKMANN(118, "David Beckmann"),
    ALESSIO_DELEDDA(121, "Alessio Deledda"),
    BENT_VISCAAL(122, "Bent Viscaal"),
    ENZO_FITTIPALDI(123, "Enzo Fittipaldi"),
    MARK_WEBBER(125, "Mark Webber"),
    JACQUES_VILLENEUVE(126, "Jacques Villeneuve"),
    JAKE_HUGHES(127, "Jake Hughes"),
    FREDERIK_VESTI(128, "Frederik Vesti"),
    OLLI_CALDWELL(129, "Olli Caldwell"),
    LOGAN_SARGEANT(130, "Logan Sargeant"),
    CEM_BOLUKBASI(131, "Cem Bolukbasi"),
    AYUMA_IWASA(132, "Ayuma Iwasa"),
    CLEMENT_NOVOLAK(133, "Clement Novolak"),
    DENNIS_HAUGER(134, "Dennis Hauger"),
    CALAN_WILLIAMS(135, "Calan Williams"),
    JACK_DOOHAN(136, "Jack Doohan"),
    AMAURY_CORDEEL(137, "Amaury Cordeel"),
    MIKA_HAKKINEN(138, "Mika Hakkinen"),
    UNKNOWN(-1, "Unknown");

    companion object {
        fun fromValue(value: Int): Driver {
            return Driver.entries.firstOrNull { it.id == value } ?: UNKNOWN
        }
    }
}
