app:
  udpListener:
    enabled: false
  packetReplay:
    enabled: true
    folder: file:./test/

spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: group_id

auto.create.topics.enable: true
